name: ci

on: push

jobs:
  build:
    name: Build code
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm i
      - run: npm run build